spring:
  application:
    name: allra
  config:
    import: optional:classpath:application-env.properties

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB.URL}
    username: ${DB.USERNAME}
    password: ${DB.PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update   # none / validate / update / create / create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true

logging:
  level:
    root: info
    org.springframework.web: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

  file:
    name: logs/spring/app.log