version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: allar_db_mysql
    environment:
      TZ: Asia/Seoul  # 서버시간 설정
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - 3306
    ports:
      - "3306:3306"
    volumes:
      - allra_mysql_data:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
      - ./init-script:/docker-entrypoint-initdb.d # sql 스크립트 디렉토리 설정
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_ai_ci
    networks:
      - allra_net
    restart: unless-stopped

volumes:
  allra_mysql_data:

networks:
  allra_net:
    driver: bridge